.github/workflows/deploy.yml
name: Deploy Telegram Bot and Web App

on:
  push:
    branches:
      - main # Kod faqat "main" branchiga push qilinganda ishga tushadi

jobs:
  deploy:
    runs-on: ubuntu-latest # Ish Ubuntu virtual mashinasida bajariladisteps:
- name: Checkout code
  uses: actions/checkout@v3 # Repository kodini olish

- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.9' # Loyihangiz uchun Python versiyasini tanlang

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt # requirements.txt dagi kutubxonalarni o'rnatish

# --- Deploy jarayoni: Heroku ga deploy qilish ---
# Bu Heroku ga deploy qilishning eng sodda yo'li.
# Agar boshqa hosting tanlasangiz, bu qism o'zgaradi.
- name: Deploy to Heroku
  env:
    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} # GitHub Secrets dan Heroku API kaliti
    HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }} # Heroku dagi ilovangiz nomi
  run: |
    # Heroku CLI ni o'rnatish
    curl https://cli-assets.heroku.com/install.sh | sh
    # Heroku ga git remote qo'shish
    heroku git:remote -a ${{ env.HEROKU_APP_NAME }}
    # Kodingizni Heroku ga push qilish
    git push heroku HEAD:main
    
